name: either
version: 0.1.0
homepage: https://github.com/JosephMoniz/dart-either
description: >
  A more expressive way to return error or success values via the type system
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  option:   0.2.1