name: either
version: 0.1.6
homepage: https://github.com/JosephMoniz/dart-either
description: >
  A more expressive way to return error or success values via the type system
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  option: '>=0.3.0 <0.4.0'
dev_dependencies:
  unittest: 0.4.7+1